{{- with .Values -}}
{{- if .podDisruptionBudget.active -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "bp.name" $ }}
  labels:
    {{- include "bp.labels" $ | nindent 4 }}
  {{ if .podDisruptionBudget.annotations -}}
  annotations:
    {{- toYaml .podDisruptionBudget.annotations | nindent 4}}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "bp.selectorLabels" $ | nindent 6 }}
  {{ if .podDisruptionBudget.maxUnavailable -}}
  maxUnavailable: {{ .podDisruptionBudget.maxUnavailable }}
  {{ end -}}
  {{ if .podDisruptionBudget.minAvailable -}}
  minAvailable: {{ .podDisruptionBudget.minAvailable }}
  {{ end -}}
{{- end -}}
{{- end -}}
