app:
  name: feed
  version: 1.0
containerTemplate:
  image: mpalu/feed
  imageTag: 1.0
  port: 3000
  env:
    USERINFO_URL: auth.app.svc.cluster.internal/api/userinfo
  resourcesLimitsCpu: 500m
  resourcesLimitsMemory: 512Mi
  resourcesRequestsCpu: 250m
  resourcesRequestsMemory: 128Mi
horizontalPodAutoscaler:
  active: true
  minReplicas: 1
  maxReplicas: 5
ingress:
  active: true
  name: feed
  backend:
    serviceName: feed
    servicePort: 3000
