apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: mpalu/auth:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8037
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
