apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: app
  labels:
    app: auth
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8037
  selector:
    app: auth
